version: "2"

services:
  web:
    build: .
# with the following line, an alternativ python app could be started
#    command: test1.py 
    ports:
      - "5001:5001"
    volumes:
      - /home/mike/docker/myStrom_API/code:/code
    restart: always
